# Site settings
title: Jekyll Project
email: hello@mustafa-watha.com
description: > # this means to ignore newlines until "baseurl:"
  Freelancer, web devloper PHP Laravel MVC Framework, JS JQUERY underscore VueJS, HTML XML, Jekyll,
  programmer Java Visual C#, network engineer cisco CCNA, System admin. Linux debian ubuntu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: mustafa_watha
github_username:  mustafawm

permalink: /:categories/:title

links:
   - title: about
     url: /about
   - title: work
     url: /work
   - title: projects
     url: /projects
   - title: hire-me
     url: /hire-me
   

# Build settings
markdown: kramdown
